#!/bin/sh
# Standartniy vivod komandi upload, nuzhno tri poslednih chisla.
# 18:44:59 up 10 min,  1 user,  load average: 0.09, 0.35, 0.35

while (true)
 do
  echo $(uptime);
  LA=$(echo $(uptime) | sed 's/:/ /g' | awk '{print "[1min LA:" $11 "] [5min LA:" $12 "] [15min LA:" $13 "]" }');
  echo $(date) $LA;
  echo $(date) $LA >> 1_st.log;
  sleep 60;
 done;