#!/bin/sh

### BEGIN INIT INFO
# Provides:          yskotov
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Write LA in file every 1 min
# Description:       Write LA information in file every 1 min
### END INIT INFO

# Здесь должен находиться основной код.
# Этот код должен обрабатывать команды start, stop и restart, переданные скрипту.
# Использование других команд не возбраняется.
# Для наглядного примера можно посмотреть любой файл из /etc/init.d/